### ISSUE TITLE
来个反向思考

### ISSUE THREAD

**Issue by qingyuan0o0** [hugefiver/fakessh#81]
如果给的假的ssh server,所有的密码都是正确的,或者给一个弱口令比如root:toor,假装让对方登录成功,是不是只会收集一次并发的数据,开始记录对方的攻击路径?然后30秒后断开,并把对方给加入到黑名单中?
[测试文件](https://github.com/qingyuan0o0/fuckssh/blob/main/main.go)
[可用文件](https://github.com/qingyuan0o0/fuckssh/blob/main/back/main.go)

**Comment by hugefiver** [comment]
通过将成功率设置为100可以达成这个目的。

>   -r float
>        success ratio float percent age (0.0 ~ 100.0, default: 0)

目前该程序只提供fakessh相关的功能，其他功能请通过监测日志文件的方式在旁路实现。
